name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'
      - name: Build modules
        run: gradle build
      - name: Run sample flow
        run: gradle run --args="replay --flow examples/sample-workflow.yaml --reportDir reports"
      - name: Publish reports
        uses: actions/upload-artifact@v4
        with:
          name: flow-reports
          path: reports
