name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'
      - name: Build modules
        run: gradle build
      - name: Create sample workflow
        run: |
          mkdir -p examples
          echo "version: '1'" > examples/sample-workflow.yaml
          echo "appVersion: 'sample'" >> examples/sample-workflow.yaml
          echo "emulator:\n  http:\n    interactions: []\n  file:\n    events: []" >> examples/sample-workflow.yaml
          echo "steps: []" >> examples/sample-workflow.yaml
      - name: Run sample flow
        run: gradle run -PmainClass=tech.softwareologists.qa.app.MainKt --args="replay --flow examples/sample-workflow.yaml --reportDir reports"
        env:
          JAVA_TOOL_OPTIONS: -Djava.awt.headless=true
      - name: Publish reports
        uses: actions/upload-artifact@v4
        with:
          name: flow-reports
          path: reports
