name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      JAVA_TOOL_OPTIONS: -Djava.awt.headless=true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'
      - name: Build
        run: gradle build
      - name: Run tests
        run: gradle test
      - name: Lint
        run: gradle ktlintCheck
      - name: Build Distributions
        run: gradle :app:packageReleaseDistributionForCurrentOS :agent:bootJar
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref_name, '-') }}
          generate_release_notes: true
          files: |
            app/build/distributions/*.zip
            agent/build/libs/*.jar
            app/build/compose/**/*.*

